### ISSUE TITLE
Great test phase separation

### ISSUE THREAD

**Issue by nduckwiler** [Vealor/codecademy-TDD-Gather-submission#1]
You separated your setup, exercise, and verify steps with blank lines. This makes the intention of your test very clear to the reader!

https://github.com/Vealor/tdd-u3-gather-pt4/blob/9460a4f33760569b672c96f054050b1720618d1c/gather-finish/test/features/user-visits-single-item-test.js#L12-L16

**Comment by Vealor** [comment]
Thank you very much! It makes it easier for me to keep track of workflow while programming too.  It allows me to do each of the steps of the tests incrementally and ensure that each of them are failing and in the red before I progress to implementation.
