### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by nduckwiler** [Vealor/codecademy-TDD-Gather-submission#2]
Careful with indentation! At Codecademy we follow [Google style guide's 2-space indentation](https://google.github.io/styleguide/jsguide.html#formatting-block-indentation), but 4-space is also fine. Either way make sure to stick to one style.

https://github.com/Vealor/tdd-u3-gather-pt4/blob/9460a4f33760569b672c96f054050b1720618d1c/gather-finish/test/features/user-visits-single-item-test.js#L4-L6

**Comment by Vealor** [comment]
Thank you for catching that.  I typically follow the 2 space indentation too.  I'd like to give you a reason why I didn't catch that, but that is my fault.  Fix found here: 21c49fb7a3b922e50a01284c8ef560416aba7c31
