### ISSUE TITLE
Use more descriptive docstrings

### ISSUE THREAD

**Issue by nduckwiler** [Vealor/codecademy-TDD-Gather-submission#3]
https://github.com/Vealor/tdd-u3-gather-pt4/blob/9460a4f33760569b672c96f054050b1720618d1c/gather-finish/test/features/user-visits-single-item-test.js#L4-L6

Docstrings are an opportunity to communicate how your application behaves &mdash; your tests can act as documentation for someone reading your code. While your above docstrings are correct, you could give more information like this:

```js
describe('User visits a single item', () => {
  describe('by clicking on a created item', () => {
    it('displays information on the item', () => {
```

In this case we know (i) which path is visited, (ii) what specific action is exercised, and (iii) what is verified.

**Comment by Vealor** [comment]
I'll be honest, I sat there trying to figure out what to actually put since I thought the interaction was so simple.  Now that you showed me what I should have put, it makes much more sense.

The way I'm understanding it is that it kind of follows a pattern of:
- destination
- action
- result

Is this correct?

**Comment by nduckwiler** [comment]
It's more important that you take one pattern and stick with it. The destination-action-result pattern is a good one to start with. It is informative, reads easily in the terminal output, and can be applied to all kinds of tests.

With these kind of decisions you can always point back to the characteristics of a good test suite: 
* maintainable
* complete
* fast
* isolated
* reliable
* expressive

Maintainable and expressive are the most applicable to docstring decisions.

**Comment by Vealor** [comment]
Understood!
