### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by nduckwiler** [Vealor/codecademy-TDD-Gather-submission#4]
Well done! Your tests are effective, concise, and clearly separated into phases. You demonstrated ability in using WebDriverIO and SuperTest.

Watch out for inconsistent indentation and use every docstring as an opportunity to better document your application. 

If you're looking for more practice, try implementing the rest of the CRUD operations: update and delete.

**Comment by Vealor** [comment]
I will implement those things in the capstone :).
